// <auto-generated />
using System;
using DogGo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogGo.Migrations
{
    [DbContext(typeof(DogGoDbContext))]
    [Migration("20260506054501_LimitesPaseadoresDatos")]
    partial class LimitesPaseadoresDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DogGo.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DueñoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaseoId")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.HasIndex("PaseoId")
                        .IsUnique();

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("DogGo.Models.DuenioPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("PreferenciasPaseo")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenciasDireccion")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Zona")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("DuenioPerfiles");
                });

            modelBuilder.Entity("DogGo.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmisorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Leido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PaseoId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("PaseoId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("DogGo.Models.Paseador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalificacionPromedio")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ExperienciaAnios")
                        .HasColumnType("int");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TarifaPorHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ZonaServicio")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Paseadores");
                });

            modelBuilder.Entity("DogGo.Models.Paseo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanceladoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionRecogida")
                        .HasColumnType("longtext");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionRealMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EsProgramado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRespuestaFinalizacionAnticipada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSolicitudFinalizacionAnticipada")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("FinalizacionAnticipadaAprobada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FinalizacionAnticipadaSolicitada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FotoFinUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoInicioUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal>("LatitudActual")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("LatitudRecogida")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("LongitudActual")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("LongitudRecogida")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoFinalizacionAnticipada")
                        .HasColumnType("longtext");

                    b.Property<int>("PaseadorId")
                        .HasColumnType("int");

                    b.Property<int>("PerroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ReferenciasRecogida")
                        .HasColumnType("longtext");

                    b.Property<string>("ZonaRecogida")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PaseadorId");

                    b.HasIndex("PerroId");

                    b.ToTable("Paseos");
                });

            modelBuilder.Entity("DogGo.Models.PaseoPerro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaseoId")
                        .HasColumnType("int");

                    b.Property<int>("PerroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerroId");

                    b.HasIndex("PaseoId", "PerroId")
                        .IsUnique();

                    b.ToTable("PaseoPerros");
                });

            modelBuilder.Entity("DogGo.Models.Perro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DueñoId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notas")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Raza")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tamaño")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.ToTable("Perros");
                });

            modelBuilder.Entity("DogGo.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<int>("PaseoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PaseoId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("DogGo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodigoConfirmacion")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("CodigoExpiraEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CodigoRecuperacion")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("CodigoRecuperacionExpiraEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DogGo.Models.Calificacion", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Dueño")
                        .WithMany()
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Paseo", "Paseo")
                        .WithOne("Calificacion")
                        .HasForeignKey("DogGo.Models.Calificacion", "PaseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");

                    b.Navigation("Paseo");
                });

            modelBuilder.Entity("DogGo.Models.DuenioPerfil", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Usuario")
                        .WithOne("DuenioPerfil")
                        .HasForeignKey("DogGo.Models.DuenioPerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DogGo.Models.Mensaje", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Emisor")
                        .WithMany("Enviados")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Paseo", "Paseo")
                        .WithMany("Mensajes")
                        .HasForeignKey("PaseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Usuario", "Receptor")
                        .WithMany("Recibidos")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Paseo");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("DogGo.Models.Paseador", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Usuario")
                        .WithOne("Paseador")
                        .HasForeignKey("DogGo.Models.Paseador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DogGo.Models.Paseo", b =>
                {
                    b.HasOne("DogGo.Models.Paseador", "Paseador")
                        .WithMany("Paseos")
                        .HasForeignKey("PaseadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Perro", "Perro")
                        .WithMany("Paseos")
                        .HasForeignKey("PerroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paseador");

                    b.Navigation("Perro");
                });

            modelBuilder.Entity("DogGo.Models.PaseoPerro", b =>
                {
                    b.HasOne("DogGo.Models.Paseo", "Paseo")
                        .WithMany("PaseoPerros")
                        .HasForeignKey("PaseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Perro", "Perro")
                        .WithMany("PaseoPerros")
                        .HasForeignKey("PerroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paseo");

                    b.Navigation("Perro");
                });

            modelBuilder.Entity("DogGo.Models.Perro", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Dueño")
                        .WithMany("Perros")
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");
                });

            modelBuilder.Entity("DogGo.Models.Ubicacion", b =>
                {
                    b.HasOne("DogGo.Models.Paseo", "Paseo")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("PaseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paseo");
                });

            modelBuilder.Entity("DogGo.Models.Paseador", b =>
                {
                    b.Navigation("Paseos");
                });

            modelBuilder.Entity("DogGo.Models.Paseo", b =>
                {
                    b.Navigation("Calificacion");

                    b.Navigation("Mensajes");

                    b.Navigation("PaseoPerros");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("DogGo.Models.Perro", b =>
                {
                    b.Navigation("PaseoPerros");

                    b.Navigation("Paseos");
                });

            modelBuilder.Entity("DogGo.Models.Usuario", b =>
                {
                    b.Navigation("DuenioPerfil");

                    b.Navigation("Enviados");

                    b.Navigation("Paseador");

                    b.Navigation("Perros");

                    b.Navigation("Recibidos");
                });
#pragma warning restore 612, 618
        }
    }
}
