// <auto-generated />
using System;
using DogGo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogGo.Migrations
{
    [DbContext(typeof(DogGoDbContext))]
    partial class DogGoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DogGo.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DueñoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaseoId")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.HasIndex("PaseoId")
                        .IsUnique();

                    b.ToTable("Calificaciones", (string)null);
                });

            modelBuilder.Entity("DogGo.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmisorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Leido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PaseoId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("PaseoId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Mensajes", (string)null);
                });

            modelBuilder.Entity("DogGo.Models.Paseador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalificacionPromedio")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TarifaPorHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Paseadores", (string)null);
                });

            modelBuilder.Entity("DogGo.Models.Paseo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LatitudActual")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("LongitudActual")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<int>("PaseadorId")
                        .HasColumnType("int");

                    b.Property<int>("PerroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaseadorId");

                    b.HasIndex("PerroId");

                    b.ToTable("Paseos", (string)null);
                });

            modelBuilder.Entity("DogGo.Models.Perro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DueñoId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<string>("Raza")
                        .HasColumnType("longtext");

                    b.Property<string>("Tamaño")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.ToTable("Perros", (string)null);
                });

            modelBuilder.Entity("DogGo.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<int>("PaseoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PaseoId");

                    b.ToTable("Ubicaciones", (string)null);
                });

            modelBuilder.Entity("DogGo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DogGo.Models.Calificacion", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Dueño")
                        .WithMany()
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Paseo", "Paseo")
                        .WithOne("Calificacion")
                        .HasForeignKey("DogGo.Models.Calificacion", "PaseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");

                    b.Navigation("Paseo");
                });

            modelBuilder.Entity("DogGo.Models.Mensaje", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Emisor")
                        .WithMany("Enviados")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Paseo", "Paseo")
                        .WithMany("Mensajes")
                        .HasForeignKey("PaseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Usuario", "Receptor")
                        .WithMany("Recibidos")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Paseo");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("DogGo.Models.Paseador", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Usuario")
                        .WithOne("Paseador")
                        .HasForeignKey("DogGo.Models.Paseador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DogGo.Models.Paseo", b =>
                {
                    b.HasOne("DogGo.Models.Paseador", "Paseador")
                        .WithMany("Paseos")
                        .HasForeignKey("PaseadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogGo.Models.Perro", "Perro")
                        .WithMany("Paseos")
                        .HasForeignKey("PerroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paseador");

                    b.Navigation("Perro");
                });

            modelBuilder.Entity("DogGo.Models.Perro", b =>
                {
                    b.HasOne("DogGo.Models.Usuario", "Dueño")
                        .WithMany("Perros")
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");
                });

            modelBuilder.Entity("DogGo.Models.Ubicacion", b =>
                {
                    b.HasOne("DogGo.Models.Paseo", "Paseo")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("PaseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paseo");
                });

            modelBuilder.Entity("DogGo.Models.Paseador", b =>
                {
                    b.Navigation("Paseos");
                });

            modelBuilder.Entity("DogGo.Models.Paseo", b =>
                {
                    b.Navigation("Calificacion")
                        .IsRequired();

                    b.Navigation("Mensajes");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("DogGo.Models.Perro", b =>
                {
                    b.Navigation("Paseos");
                });

            modelBuilder.Entity("DogGo.Models.Usuario", b =>
                {
                    b.Navigation("Enviados");

                    b.Navigation("Paseador")
                        .IsRequired();

                    b.Navigation("Perros");

                    b.Navigation("Recibidos");
                });
#pragma warning restore 612, 618
        }
    }
}
